# Generated by Django 5.2.5 on 2025-09-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shoppingcard_ordercard'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(to='shop.product', verbose_name='Favori Ürünler'),
        ),
    ]
