# Generated by Django 5.2.5 on 2025-09-06 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori İsmi')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('color1', 'Yeşil'), ('color2', 'Kırmızı'), ('color3', 'Mavi'), ('color4', 'Siyah'), ('color5', 'Pembe')], max_length=100)),
                ('code', models.CharField(max_length=7)),
                ('code2', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('feature', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('size1', 'S'), ('size2', 'M'), ('size3', 'XL'), ('size4', '2XL')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ürün İsmi')),
                ('price', models.IntegerField(verbose_name='Fiyat')),
                ('discounted', models.IntegerField(verbose_name='İndirimli Fiyat')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory', verbose_name='Kategori')),
                ('colors', models.ManyToManyField(blank=True, null=True, to='shop.productcolor', verbose_name='Ürün Renkleri')),
                ('features', models.ManyToManyField(blank=True, null=True, to='shop.productfeatures', verbose_name='Ürün Özellikleri')),
                ('images', models.ManyToManyField(to='shop.productimage', verbose_name='Resimler')),
                ('sizes', models.ManyToManyField(to='shop.productsize', verbose_name='Ürün Bedenleri')),
            ],
        ),
    ]
