# Generated by Django 5.2.5 on 2025-09-09 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Ürün Adeti')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Ürün Eklenme Tarihi')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcolor', verbose_name='Ürün Rengi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='Ürün')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productcategory', verbose_name='Ürün Bedeni')),
            ],
        ),
    ]
