# Generated by Django 5.2.5 on 2025-09-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(to='shop.productimage', verbose_name='Resimler'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted',
            field=models.IntegerField(verbose_name='İndirimli Fiyat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Fiyat'),
        ),
    ]
