# Generated by Django 5.2.5 on 2025-09-09 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderitem_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sepet Oluşturulma Tarihi')),
                ('ordered', models.BooleanField(default=False, verbose_name='Sipariş Edilme Durumu')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
                ('orders', models.ManyToManyField(to='shop.orderitem', verbose_name='Ürünler')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Edilme Tarihi')),
                ('complete', models.BooleanField(default=False, verbose_name='Tamamlanma Durumu')),
                ('shoppingcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shoppingcard', verbose_name='Alışveriş Sepeti')),
            ],
        ),
    ]
