# Generated by Django 5.2.5 on 2025-09-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcolor',
            name='code2',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
