# Generated by Django 5.2.5 on 2025-09-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productcolor_code_productcolor_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='code2',
            field=models.CharField(max_length=7),
        ),
    ]
